apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  rules:
    - host: spring-boot.davidcamelo.com
      http:
        paths:
          - backend:
              service:
                name: api-gateway
                port:
                  name: 8080